const { chromium } = require('playwright');
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async () => {
  fs.mkdirSync('qa', { recursive: true });
  const server = spawn('python3', ['-m', 'http.server', '8765', '--directory', 'build/web']);
  let browser;
  let page;
  const errors = [];
  try {
    browser = await chromium.launch({ args: ['--enable-unsafe-swiftshader', '--use-angle=swiftshader', '--no-sandbox'] });
    page = await browser.newPage({ viewport: { width: 1280, height: 720 }, hasTouch: true });
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', msg => { console.log('BROWSER:',msg.type(),msg.text()); if (/SCRIPT ERROR|Parse Error|ERROR:/.test(msg.text())) errors.push(msg.text()); });
    await page.goto('http://127.0.0.1:8765/?qa=1');
    await page.waitForTimeout(3000);
    await page.screenshot({path:'qa/startup.png'});
    console.log('STARTUP DOM:',await page.locator('body').innerText());
    await page.waitForFunction(() => !!document.querySelector('canvas')?.dataset.aervalon, null, { timeout: 60000 });
    const readState = () => page.locator('canvas').evaluate(el => JSON.parse(el.dataset.aervalon));
    await page.waitForTimeout(1500);
    assert.equal((await readState()).menu,true,'Fresh install opens character creation');
    assert.equal((await readState()).world_loaded,false,'Title screen does not load the gameplay map');
    assert.equal((await readState()).selected_class,'guardian','Fresh character creation defaults to Guardian');
    for (const race of ['Sylari','Kharum','Ruun','Nym','Thalass','Pipri','Valen']) {
      await pressUI(race);
      assert.equal((await readState()).selected_race,race.toLowerCase(),'Race choice updates identity');
      await page.screenshot({path:'qa/race-'+race.toLowerCase()+'.png'});
    }
    await page.screenshot({path:'qa/character-creation.png'});
    await pressUI('Nome do personagem');
    await page.keyboard.insertText('Arin');
    await pressUI('Criar personagem');
    await pressUI('Entrar em Eryndor');
    await page.waitForFunction(() => JSON.parse(document.querySelector('canvas').dataset.aervalon).menu===false);
    assert.equal((await readState()).character_name,'Arin','Named character enters the world');
    await page.screenshot({ path: 'qa/eryndor-village.png' });
    await page.keyboard.press('e');
    await page.waitForTimeout(300);
    await page.screenshot({ path: 'qa/eryndor-mara.png' });
    assert.equal((await readState()).quest_started, true, 'Keyboard dialogue starts Mara quest');
    await page.keyboard.press('i');
    await page.waitForTimeout(200);
    assert.equal((await readState()).modal,true,'Inventory opens');
    await page.screenshot({path:'qa/inventory-desktop.png'});
    await page.keyboard.press('Escape');
    await page.keyboard.press('Space');
    await page.waitForTimeout(150);
    await page.screenshot({ path: 'qa/eryndor-attack.png' });
    // Walk to the actual merchant, interact, then buy through rendered buttons.
    async function walkAxis(axis,target,keyPositive,keyNegative) {
      for(let attempt=0;attempt<30;attempt++) {
        const state=await readState();
        const offset=target-state.position[axis];
        if(Math.abs(offset)<12) return;
        const key=offset>0?keyPositive:keyNegative;
        await page.keyboard.down(key);
        await page.waitForTimeout(Math.min(450,Math.max(120,Math.abs(offset)/170*1000)));
        await page.keyboard.up(key);
        await page.waitForTimeout(180);
      }
      throw new Error('Walking failed to reach '+target+': '+JSON.stringify(await readState()));
    }
    await walkAxis(0,500,'d','a');
    await walkAxis(1,650,'s','w');
    await page.keyboard.press('e');
    await page.waitForTimeout(250);
    assert.equal((await readState()).shop,'merchant','Nearby merchant opens actual shop');
    async function pressUI(prefix) {
      const state=await readState();
      const entry=Object.entries(state.buttons).find(([text])=>text.startsWith(prefix));
      assert.ok(entry,'Visible UI button: '+prefix);
      assert.ok(entry[1][0]>=0 && entry[1][0]<=state.viewport[0] && entry[1][1]>=0 && entry[1][1]<=state.viewport[1],'UI button inside viewport: '+prefix);
      const bounds=await page.locator('canvas').boundingBox();
      await page.mouse.click(bounds.x+entry[1][0]/state.viewport[0]*bounds.width,bounds.y+entry[1][1]/state.viewport[1]*bounds.height);
      await page.waitForTimeout(200);
    }
    await pressUI('Poção');
    await pressUI('Comprar •');
    assert.equal((await readState()).coins,4,'Shop UI deducts potion price');
    assert.equal((await readState()).inventory.potion,3,'Shop UI adds bought potion');
    await page.screenshot({path:'qa/shop-merchant.png'});
    await page.setViewportSize({width:844,height:390});
    await page.waitForTimeout(400);
    await page.screenshot({path:'qa/shop-mobile.png'});
    await page.setViewportSize({width:1280,height:720});
    await page.waitForTimeout(400);
    await page.keyboard.press('Escape');
    await walkAxis(1,450,'s','w'); // Stand at the forge frontage, outside Mara's wandering interaction area.
    await walkAxis(0,670,'d','a');
    await page.keyboard.press('e');
    await page.waitForTimeout(250);
    assert.equal((await readState()).shop,'borin','Borin is reachable from the forge frontage');
    await page.screenshot({path:'qa/shop-borin.png'});
    await page.keyboard.press('Escape');
    // New exploration uses the actual nearby-object button, no QA mutations.
    await walkAxis(0,760,'d','a'); // Clear the well footprint with room for the player's body.
    await walkAxis(1,710,'s','w');
    assert.equal((await readState()).interaction,'herb_village','Plant has a comfortable contextual radius');
    await page.keyboard.press('e');
    await page.waitForTimeout(300);
    assert.equal((await readState()).inventory.river_herb,1,'Gathering adds a usable herb');
    assert.equal((await readState()).herbalism,1,'Practice increases through gathering');
    await page.keyboard.press('e');
    await page.waitForTimeout(200);
    assert.equal((await readState()).inventory.river_herb,1,'Plant cannot be harvested twice immediately');
    await page.screenshot({path:'qa/gathering.png'});
    await walkAxis(1,835,'s','w');
    assert.equal((await readState()).interaction,'well_echo','Well discovery is physically reachable');
    await page.keyboard.press('e');
    await page.waitForTimeout(300);
    assert.equal((await readState()).discoveries.well_echo,true,'World discovery is recorded');
    await page.screenshot({path:'qa/well-echo.png'});
    // Return to open village ground for the mobile joystick test.
    await walkAxis(1,600,'s','w');
    await walkAxis(0,650,'d','a'); // Leave room for joystick movement AND the dodge before the river.
    await page.setViewportSize({ width: 844, height: 390 });
    await page.waitForTimeout(400);
    await page.screenshot({ path: 'qa/eryndor-mobile.png' });
    await page.keyboard.press('i');
    await page.waitForTimeout(250);
    await page.screenshot({path:'qa/inventory-mobile.png'});
    assert.equal((await readState()).modal,true,'Inventory opens in mobile viewport');
    await page.keyboard.press('Escape');
    const cdp = await page.context().newCDPSession(page);
    const before = await readState();
    const bounds = await page.locator('canvas').boundingBox();
    const cssPoint = p => ({x:bounds.x+p[0]/before.viewport[0]*bounds.width,y:bounds.y+p[1]/before.viewport[1]*bounds.height});
    const joy = cssPoint(before.joystick);
    const stick = cssPoint([before.joystick[0]+52,before.joystick[1]]);
    const attack = cssPoint(before.attack);
    await cdp.send('Input.dispatchTouchEvent', {type:'touchStart',touchPoints:[{...joy,id:0}]});
    await cdp.send('Input.dispatchTouchEvent', {type:'touchMove',touchPoints:[{...stick,id:0}]});
    await page.waitForTimeout(800);
    assert.ok((await readState()).position[0] > before.position[0]+20, 'Touch joystick moves hero');
    await cdp.send('Input.dispatchTouchEvent', {type:'touchStart',touchPoints:[{...stick,id:0},{...attack,id:1}]});
    await page.waitForTimeout(150);
    await cdp.send('Input.dispatchTouchEvent', {type:'touchEnd',touchPoints:[]});
    await page.screenshot({ path: 'qa/eryndor-mobile-move.png' });
    const dodge = cssPoint((await readState()).dodge);
    await page.waitForTimeout(700);
    const beforeDodge = await readState();
    await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...dodge,id:0}]});
    await page.waitForTimeout(150);
    await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
    await page.waitForFunction(() => { const s=JSON.parse(document.querySelector('canvas').dataset.aervalon); return s.dodge_cooldown>0 && s.dodge_cooldown<1; }, null, {timeout:5000});
    const afterDodge = await readState();
    assert.ok(afterDodge.dodge_cooldown>0,'Mobile dodge button starts cooldown');
    assert.ok(afterDodge.position[0]>beforeDodge.position[0]+15,'Touch dodge physically displaces player');
    await page.screenshot({path:'qa/dodge-mobile.png'});
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(300);
    await page.screenshot({ path: 'qa/eryndor-portrait.png' });
    assert.equal((await readState()).portrait,true,'Portrait rotation notice is visible');
    await page.reload();
    await page.waitForFunction(() => !!document.querySelector('canvas')?.dataset.aervalon, null, { timeout: 60000 });
    assert.equal((await readState()).quest_started,true,'Web refresh keeps quest progress');
    assert.equal((await readState()).equipment.weapon,'rusty_sword','Web refresh keeps equipment');
    assert.equal((await readState()).herbalism,1,'Web refresh keeps profession practice');
    assert.equal((await readState()).discoveries.well_echo,true,'Web refresh keeps discovery');
    assert.equal((await readState()).inventory.river_herb,1,'Web refresh keeps collected resources');
    await page.setViewportSize({width:844,height:390});
    await page.waitForTimeout(400);
    await page.screenshot({path:'qa/character-selection-mobile.png'});
    await pressUI('Novo personagem');
    await pressUI('Nome do personagem');
    await page.keyboard.insertText('Nora');
    await pressUI('Nym');
    await pressUI('Arcanista');
    assert.equal((await readState()).selected_class,'arcanist','Class selector changes persistent identity');
    await pressUI('Criar personagem');
    await pressUI('Entrar em Eryndor');
    await page.waitForFunction(() => {const s=JSON.parse(document.querySelector('canvas').dataset.aervalon); return !s.menu && s.character_name==='Nora';});
    assert.equal((await readState()).coins,12,'Second character has independent starting coins');
    assert.equal((await readState()).race,'nym','Selected Nym race enters gameplay');
    assert.equal((await readState()).visual_race,'nym','Actual player animation uses Nym identity');
    assert.equal((await readState())['class'],'arcanist','Selected Arcanist class enters gameplay');
    await page.keyboard.press('q');
    await page.waitForTimeout(150);
    assert.ok((await readState()).power_cooldown>0,'Class power is playable from keyboard');
    await page.keyboard.down('d');
    await page.waitForTimeout(250);
    await page.keyboard.up('d');
    await page.screenshot({path:'qa/nym-gameplay-mobile.png'});
    assert.equal((await readState()).quest_started,false,'Second character starts a separate quest');
    assert.equal((await readState()).inventory.river_herb,undefined,'Second character does not inherit loot');
    await page.keyboard.press('i');
    await page.waitForTimeout(250);
    await pressUI('Personagem');
    await page.screenshot({path:'qa/character-sheet-mobile.png'});
    await pressUI('Personagens');
    await page.waitForFunction(() => JSON.parse(document.querySelector('canvas').dataset.aervalon).menu===true);
    await pressUI('Arin');
    await pressUI('Entrar em Eryndor');
    await page.waitForFunction(() => {const s=JSON.parse(document.querySelector('canvas').dataset.aervalon); return !s.menu && s.character_name==='Arin';});
    assert.equal((await readState()).coins,4,'Returning to first character restores its coins');
    assert.equal((await readState()).discoveries.well_echo,true,'Returning to first character restores its discoveries');
    await page.keyboard.press('i');
    await page.waitForTimeout(250);
    await pressUI('Personagem');
    await pressUI('Personagens');
    await page.waitForFunction(()=>JSON.parse(document.querySelector('canvas').dataset.aervalon).scene==='title');
    await pressUI('Nora');
    await pressUI('Excluir personagem');
    await page.screenshot({path:'qa/delete-confirmation-mobile.png'});
    await pressUI('Cancelar exclusão');
    assert.equal(Object.keys((await readState()).profiles).length,2,'Cancelling deletion preserves both profiles');
    await pressUI('Excluir personagem');
    await pressUI('Excluir definitivamente');
    assert.equal(Object.keys((await readState()).profiles).length,1,'Confirmed deletion removes only chosen profile');
    await pressUI('Entrar em Eryndor');
    await page.waitForFunction(()=>JSON.parse(document.querySelector('canvas').dataset.aervalon).menu===false);
    assert.equal((await readState()).character_name,'Arin','Other character remains playable after deletion');
    assert.equal((await readState()).coins,4,'Deletion preserves surviving character progress');
    const legacy={version:1,level:3,xp:7,coins:87,inventory:{rusty_sword:1,iron_sword:1,leather_armor:1,potion:2},equipment:{weapon:'iron_sword',armor:''},quest:'complete',kills:3,chest_open:true};
    const legacyContext=await browser.newContext({viewport:{width:844,height:390},hasTouch:true});
    await legacyContext.addInitScript(data=>localStorage.setItem('aervalon.eryndor.v1',JSON.stringify(data)),legacy);
    page=await legacyContext.newPage();
    page.on('pageerror',error=>errors.push(error.message));
    page.on('console',msg=>{if(/SCRIPT ERROR|Parse Error|ERROR:/.test(msg.text())) errors.push(msg.text());});
    await page.goto('http://127.0.0.1:8765/?qa=1');
    await page.waitForFunction(()=>!!document.querySelector('canvas')?.dataset.aervalon,null,{timeout:60000});
    assert.equal((await readState()).coins,87,'Legacy migration preserves wealth');
    assert.equal((await readState()).complete,true,'Legacy migration preserves completed quest');
    assert.equal((await readState()).equipment.weapon,'iron_sword','Legacy migration preserves equipped weapon');
    await pressUI('Entrar em Eryndor');
    await page.waitForFunction(()=>JSON.parse(document.querySelector('canvas').dataset.aervalon).menu===false);
    await page.keyboard.press('i');
    await page.waitForTimeout(250);
    await pressUI('Armadura');
    await pressUI('Equipar');
    assert.equal((await readState()).equipment.armor,'leather_armor','Inventory UI equips armor');
    await pressUI('Personagem');
    await page.screenshot({path:'qa/leather-sheet-mobile.png'});
    await pressUI('Retirar armadura');
    assert.equal((await readState()).equipment.armor,'','Character sheet removes armor');
    await pressUI('Fechar');
    assert.equal((await readState()).modal,false,'Equipment sheet close button stays reachable on mobile');
    const originalSave=await page.evaluate(()=>JSON.parse(localStorage.getItem('aervalon.eryndor.v1')));
    assert.deepEqual(originalSave,legacy,'Original save remains untouched as backup');
    await page.keyboard.press('i');
    await page.waitForTimeout(250);
    await pressUI('Personagem');
    await pressUI('Personagens');
    await page.waitForFunction(()=>JSON.parse(document.querySelector('canvas').dataset.aervalon).scene==='title');
    await pressUI('Excluir personagem');
    await pressUI('Excluir definitivamente');
    await page.reload();
    await page.waitForFunction(()=>!!document.querySelector('canvas')?.dataset.aervalon,null,{timeout:60000});
    assert.equal(Object.keys((await readState()).profiles).length,0,'Deleting last profile survives refresh without legacy resurrection');
    assert.equal((await readState()).world_loaded,false,'Empty roster stays on independent title scene');
    await page.screenshot({path:'qa/empty-roster-mobile.png'});
    assert.deepEqual(errors, [], 'No Godot or JavaScript runtime errors');
    fs.writeFileSync('qa/browser-result.json', JSON.stringify({passed:true,errors,viewports:['1280x720','844x390','390x844']},null,2));
    console.log('PASS: WebGL2 startup, keyboard interaction/attack, landscape/portrait layout, multitouch input, no runtime errors');
  } catch(error) {
    if(page) {
      await page.screenshot({path:"qa/failure.png"}).catch(()=>{});
      console.log("FAILURE DOM:",await page.locator("body").innerText().catch(()=>"unavailable"));
    }
    throw error;
  } finally {
    if (browser) await browser.close();
    server.kill();
    fs.writeFileSync('qa/console-errors.json', JSON.stringify(errors,null,2));
  }
})().catch(error => { console.error(error); process.exit(1); });
