const { chromium } = require('playwright');
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async () => {
  fs.mkdirSync('qa', { recursive: true });
  const server = spawn('python3', ['-m', 'http.server', '8765', '--directory', 'build/web']);
  let browser;
  const errors = [];
  try {
    browser = await chromium.launch({ args: ['--enable-unsafe-swiftshader', '--use-angle=swiftshader', '--no-sandbox'] });
    const page = await browser.newPage({ viewport: { width: 1280, height: 720 }, hasTouch: true });
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', msg => { if (/SCRIPT ERROR|Parse Error|ERROR:/.test(msg.text())) errors.push(msg.text()); });
    await page.goto('http://127.0.0.1:8765/?qa=1');
    await page.waitForFunction(() => !!document.querySelector('canvas')?.dataset.aervalon, null, { timeout: 60000 });
    const readState = () => page.locator('canvas').evaluate(el => JSON.parse(el.dataset.aervalon));
    await page.waitForTimeout(1500);
    await page.screenshot({ path: 'qa/eryndor-village.png' });
    await page.keyboard.press('e');
    await page.waitForTimeout(300);
    await page.screenshot({ path: 'qa/eryndor-mara.png' });
    assert.equal((await readState()).quest_started, true, 'Keyboard dialogue starts Mara quest');
    await page.keyboard.press('Space');
    await page.waitForTimeout(150);
    await page.screenshot({ path: 'qa/eryndor-attack.png' });
    await page.setViewportSize({ width: 844, height: 390 });
    await page.waitForTimeout(400);
    await page.screenshot({ path: 'qa/eryndor-mobile.png' });
    const cdp = await page.context().newCDPSession(page);
    const before = await readState();
    const bounds = await page.locator('canvas').boundingBox();
    const cssPoint = p => ({x:bounds.x+p[0]/before.viewport[0]*bounds.width,y:bounds.y+p[1]/before.viewport[1]*bounds.height});
    const joy = cssPoint(before.joystick);
    const stick = cssPoint([before.joystick[0]+52,before.joystick[1]]);
    const attack = cssPoint(before.attack);
    await cdp.send('Input.dispatchTouchEvent', {type:'touchStart',touchPoints:[{...joy,id:0}]});
    await cdp.send('Input.dispatchTouchEvent', {type:'touchMove',touchPoints:[{...stick,id:0}]});
    await page.waitForTimeout(800);
    assert.ok((await readState()).position[0] > before.position[0]+20, 'Touch joystick moves hero');
    await cdp.send('Input.dispatchTouchEvent', {type:'touchStart',touchPoints:[{...stick,id:0},{...attack,id:1}]});
    await page.waitForTimeout(150);
    await cdp.send('Input.dispatchTouchEvent', {type:'touchEnd',touchPoints:[]});
    await page.screenshot({ path: 'qa/eryndor-mobile-move.png' });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(300);
    await page.screenshot({ path: 'qa/eryndor-portrait.png' });
    assert.equal((await readState()).portrait,true,'Portrait rotation notice is visible');
    assert.deepEqual(errors, [], 'No Godot or JavaScript runtime errors');
    fs.writeFileSync('qa/browser-result.json', JSON.stringify({passed:true,errors,viewports:['1280x720','844x390','390x844']},null,2));
    console.log('PASS: WebGL2 startup, keyboard interaction/attack, landscape/portrait layout, multitouch input, no runtime errors');
  } finally {
    if (browser) await browser.close();
    server.kill();
    fs.writeFileSync('qa/console-errors.json', JSON.stringify(errors,null,2));
  }
})().catch(error => { console.error(error); process.exit(1); });
