extends RefCounted
# Stable class IDs belong to character profiles. Weapon families define combat identity.
const ALL = {
	"guardian":{"name":"Guardião","weapons":"Espada, machado ou maça + escudo","specializations":"Bastião • Conquistador • Vanguarda","description":"Linha de frente resistente, feita para controlar espaço e proteger aliados.","families":["blade","axe","mace"],"starter":"rusty_sword","attack_bonus":0,"defense_bonus":2,"health_bonus":20,"speed":165.0,"attack_cooldown":0.58,"attack_range":88.0,"power":"Bastião","power_desc":"Reduz fortemente o próximo dano por alguns segundos.","power_cooldown":8.0},
	"shadow":{"name":"Sombra","weapons":"Duas adagas ou espadas curtas","specializations":"Assassino • Veneno • Espectro","description":"Combate rápido de curta distância, com pressão e reposicionamento.","families":["dagger","short_blade"],"starter":"shadow_daggers","attack_bonus":4,"defense_bonus":0,"health_bonus":-10,"speed":190.0,"attack_cooldown":0.38,"attack_range":82.0,"power":"Duplo Corte","power_desc":"Executa duas passagens rápidas à frente.","power_cooldown":6.0},
	"tracker":{"name":"Rastreador","weapons":"Arco, besta ou rifle + faca/pet","specializations":"Atirador • Domador • Caçador","description":"Caçador móvel que domina distância, trilhas e companheiros.","families":["bow","crossbow","firearm","dagger"],"starter":"tracker_bow","attack_bonus":2,"defense_bonus":0,"health_bonus":0,"speed":178.0,"attack_cooldown":0.62,"attack_range":96.0,"power":"Tiro Longo","power_desc":"Disparo preciso de grande alcance em linha reta.","power_cooldown":6.5},
	"arcanist":{"name":"Arcanista","weapons":"Cajado ou varinha + grimório","specializations":"Chama • Gelo • Arcano","description":"Canalizador de magia ofensiva, forte em área e controle.","families":["staff","wand"],"starter":"arcanist_staff","attack_bonus":5,"defense_bonus":0,"health_bonus":-8,"speed":168.0,"attack_cooldown":0.60,"attack_range":92.0,"power":"Rajada Arcana","power_desc":"Detona energia num círculo à frente.","power_cooldown":7.0},
	"luminar":{"name":"Luminar","weapons":"Maça/escudo, martelo ou cetro + livro","specializations":"Graça • Juramento • Julgamento","description":"Combatente sagrado capaz de suportar dano e restaurar vida.","families":["mace","hammer","scepter"],"starter":"luminar_mace","attack_bonus":1,"defense_bonus":1,"health_bonus":12,"speed":164.0,"attack_cooldown":0.56,"attack_range":88.0,"power":"Luz Vital","power_desc":"Recupera parte importante da própria vida.","power_cooldown":9.0},
	"bound":{"name":"Vinculado","weapons":"Cajado, lança ou foice + talismã","specializations":"Fera • Vida • Espírito","description":"Canaliza vínculos vivos para ferir, sustentar e adaptar-se.","families":["staff","spear","scythe"],"starter":"bound_spear","attack_bonus":2,"defense_bonus":0,"health_bonus":8,"speed":176.0,"attack_cooldown":0.54,"attack_range":102.0,"power":"Vínculo Feral","power_desc":"Fere um alvo próximo e recupera parte da força.","power_cooldown":7.5},
	"veil":{"name":"Velário","weapons":"Cajado, adaga ou foice","specializations":"Ossos • Ecos • Sangue","description":"Manipula ecos vitais e luta no limite entre dano e sustentação.","families":["staff","dagger","scythe"],"starter":"veil_scythe","attack_bonus":3,"defense_bonus":0,"health_bonus":0,"speed":170.0,"attack_cooldown":0.52,"attack_range":98.0,"power":"Dreno de Eco","power_desc":"Rouba vida do inimigo mais próximo.","power_cooldown":8.0},
	"artificer":{"name":"Artífice","weapons":"Pistola ou rifle + ferramenta/dispositivo","specializations":"Artilheiro • Mecânico • Demolidor","description":"Tecnólogo de campo que transforma preparação em dano explosivo.","families":["firearm"],"starter":"artificer_pistol","attack_bonus":3,"defense_bonus":0,"health_bonus":0,"speed":168.0,"attack_cooldown":0.64,"attack_range":92.0,"power":"Carga de Oficina","power_desc":"Detona uma carga no ponto à frente.","power_cooldown":8.0},
	"storm":{"name":"Tempestário","weapons":"Lança, machado ou martelo + foco","specializations":"Tempestade • Terra • Maré","description":"Guerreiro elemental que converte proximidade em impacto de área.","families":["spear","axe","hammer"],"starter":"storm_spear","attack_bonus":2,"defense_bonus":1,"health_bonus":8,"speed":172.0,"attack_cooldown":0.56,"attack_range":104.0,"power":"Pulso de Tempestade","power_desc":"Libera uma descarga ao redor do personagem.","power_cooldown":7.5},
	"echo":{"name":"Ecoante","weapons":"Lâmina ou bastão + foco","specializations":"Tempo • Memória • Ruptura","description":"Manipula ritmo e memória de combate para quebrar janelas de tempo.","families":["blade","staff"],"starter":"echo_blade","attack_bonus":2,"defense_bonus":0,"health_bonus":0,"speed":181.0,"attack_cooldown":0.48,"attack_range":92.0,"power":"Ruptura","power_desc":"Libera imediatamente ataque e esquiva.","power_cooldown":9.0}
}
